name: "Ruby CI"
on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1 # v1.146.0
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Install Gems
        run: |
          gem install bundler
          bundle install
      - name: Run tests
        run: bundle exec rspec spec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1 # v1.146.0
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Install rubocop
        run: gem install rubocop
      - name: Install bundler-audit
        run: gem install bundler-audit
      - name: Security audit dependencies
        run: bundle audit check --update
      - name: Lint Ruby files
        run: rubocop --parallel -l
